// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRzo0b1AJW1IcHcIcjiZ3hI6JkmzjkiMc',
    appId: '1:218593609733:web:f9c9c398d862c5472ab46c',
    messagingSenderId: '218593609733',
    projectId: 'acrobatics-app',
    authDomain: 'acrobatics-app.firebaseapp.com',
    storageBucket: 'acrobatics-app.appspot.com',
    measurementId: 'G-2SCPSC8066',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2uwBnIxS_FQZpgtBzQxCRrMek4fLl0bA',
    appId: '1:218593609733:android:6c4e412b4add15252ab46c',
    messagingSenderId: '218593609733',
    projectId: 'acrobatics-app',
    storageBucket: 'acrobatics-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvcxNSFIgqWVCtuIcsF8tbRxE1op1VpJA',
    appId: '1:218593609733:ios:e2c90b0ed98007ae2ab46c',
    messagingSenderId: '218593609733',
    projectId: 'acrobatics-app',
    storageBucket: 'acrobatics-app.appspot.com',
    iosBundleId: 'com.example.chatui',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvcxNSFIgqWVCtuIcsF8tbRxE1op1VpJA',
    appId: '1:218593609733:ios:e2c90b0ed98007ae2ab46c',
    messagingSenderId: '218593609733',
    projectId: 'acrobatics-app',
    storageBucket: 'acrobatics-app.appspot.com',
    iosBundleId: 'com.example.chatui',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRzo0b1AJW1IcHcIcjiZ3hI6JkmzjkiMc',
    appId: '1:218593609733:web:82075f6c24a713dd2ab46c',
    messagingSenderId: '218593609733',
    projectId: 'acrobatics-app',
    authDomain: 'acrobatics-app.firebaseapp.com',
    storageBucket: 'acrobatics-app.appspot.com',
    measurementId: 'G-M9QQB16G7W',
  );

}